### PR TITLE
Add deploy task

### LINKED ISSUE #12: Restore deploy task

### PR DESCRIPTION
**Pull request by tonifisler**
Will close #12

### CODE REVIEW

**Comment by Yago** [comment]
I'll test this one asap 😉

**Comment by tonifisler** [comment]
@Yago When is asap? 😇 

I'll merge this tomorrow :)

**Comment by zufrieden** [comment]
@tonifisler 
Works for me ;-)
```
yarn deploy
yarn deploy v0.21.3
$ toolbox deploy
[22:02:54] Using gulpfile ~/dev/interaction18-styleguide/node_modules/toolbox-utils/gulpfile.js
[22:02:54] Starting 'deploy'...
[22:03:02] [gh-pages] Cloning repo
[22:03:02] [gh-pages] Checkout remote branch `gh-pages`
[22:03:02] [gh-pages] Updating repository
[22:03:06] [gh-pages] Copying files to repository
[22:03:07] [gh-pages] Adding 176 files.
[22:03:07] [gh-pages] Committing "Update 2017-09-04T20:02:54.824Z"
[22:03:07] [gh-pages] Pushing to remote.
[22:03:14] Finished 'deploy' after 19 s
✨  Done in 22.12s.
```

**Comment by Yago** [comment]
Yes ! Die in hell Prettier 🔥 🔥 🔥 🔥 🔥 🔥

**Pull request merged**
